name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    uses: 1mb-dev/.github/.github/workflows/ci-node.yml@main
    with:
      node-versions: '["22"]'
      run-audit: true
